---
- name: "Provision vuln0"
  hosts: all
  become: true

  tasks:
  - name: Set hostname
    hostname:
      name: vuln0

  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest

  - name: Download MoinMoin
    get_url:
      url: https://www.exploit-db.com/apps/adfa15e3e37cf26b4b014f209959e9d9-moin-1.9.5.tar.gz
      dest: /opt/moin-1.9.5.tar.gz

  - name: Unpack MoinMoin source
    shell:
      cmd: cd /opt/ && gunzip moin-1.9.5.tar.gz

  - name: Unpack MoinMoin source
    shell:
      cmd: cd /opt/ && tar xvf moin-1.9.5.tar

  - name: Run MoinMoin setup
    shell:
      cmd: cd /opt/moin-1.9.5 && python setup.py install

  - name: Make MoinMoin listen on all interfaces
    replace:
      path: /opt/moin-1.9.5/wikiserverconfig.py
      regexp: 'localhost'
      replace: ""

  - name: Copy MoinMoin service
    copy:
        src: moinmoin.service
        dest: /etc/systemd/system/moinmoin.service

  - name: Start MoinMoin
    systemd:
      state: started
      name: moinmoin.service
      enabled: yes

  - name: Start Apache
    systemd:
      state: started
      name: httpd
      enabled: yes

  - name: Copy index file
    copy:
        src: index.html
        dest: /var/www/html

  - name: Add MoinMoin CronJob
    cron:
      name: "Restart MoinMoin Service"
      job: "systemctl restart moinmoin.service"
      minute: "*/5"

  - name: Change directory permissions
    file:
      path: /usr/local/bin
      state: directory
      mode: '0777'

  - name: Add Path Checker CronJob
    cron:
      name: "Check Path Checker"
      job: "PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/conda/.local/bin:/home/conda/bin:/root/bin cat $PATH"
      user: root
      cron_file: path_checker

  - name: Remove the user "conda" from the wheel group
    user:
      name: conda
      groups: conda
      append: no

  - name: Change conda password
    user:
      name: conda
      update_password: always
      password: '!'

  - name: Remove sudo access from conda
    lineinfile:
      path: /etc/sudoers
      regexp: '^conda'
      line: 'conda ALL= NOPASSWD: /sbin/halt' 